
CREATE TABLE EVALUACION ( ID_CALIFICACION INTEGER PRIMARY KEY AUTO_INCREMENT,
                            NOMBRE VARCHAR(120),
                            CALIFICACION FLOAT



);
SELECT * FROM EVALUACION;